language: node_js
node_js:
- '12'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: pfh-copy
  api_key:
    secure: 6tgGkOR2dddupuOFSzBJob86jGt5bJNiABCTUQnWt4yDMtGZ2MEtFjY3tUyyfPmJHcyXjGmzxwElxsWriqjHIMbQDWmulx232TlfUONW3VZCaZO/MScJWhSpvOD4TuglyXc/qqJHmZpnk///xMcpZsA4dEfuPIGIuJdGKm07ApyJCAXEOVXcbnN2IO+r8PinxpzykR31jYVo55+rTGe2SD9B0IAiH/lh3OxH0Ye1QqrBmq+rWxKzRG4/LhBQDKcEZsmWjAV7/u1ZAEn8q6JmZoppRwO7lfum82xhMhyibNMRRpt3UY5/OPjqOKH2J4WEZgTZsBEW4P3Z1BxCTjLxghmv4xh4pBImXPGpVi90slC9o5LEIUql9OuG7ObuU3hd5PufKm0GbHtfL5kFp1Nv8at0qFzRGOoTvGYk9m/122k0Rj41GUYy+Ben+fhTPmHDOIB7f6DyGIW3OyliimnSbOs7rz4QqHFqd2g9Z9SUnRSbdxU3HvtfA6kiL8vdb9cUSxAX5AXXiFfSG567grBdkceSNUZ4mJHqkGzshWb0ctceDD866/y5xqR11rjTk741BdmX2ejn/PyHgZUGK63zH1LZ5ATI0Tr4z6W9y9pQK7+C6UC937i+WYztf8eghaQf11DSjW0r5JEl/oUW58wkWUwxdykRkL8SsAuGQx2CcmA=
