language: node_js
node_js:
- '12'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: real-super-cool-modern-app-wfh
  api_key:
    secure: P1NrUXQB/gGB3IltSo7PvsOVcTiWFUsAsLKjN2a3a8D0SFuDzJrNY8LPrqURzbLi2g3XgT7BF4lhNQ6KDfnlej+P7y8OBxZsNlthQTPqKj7u2otOb+SRzjGWgXWcMRvD7IHzKsRLk1IY/KQNGLjGIGkHM1yNbbX2Rc/FjKGawF2iyxYhvQZmaaH8rnWvj7chyvguErNXPG7QUGsJCXhu3XOgneILVVmSnEIwX6ShaZgsRUpduG3DX3T48hvXrNlDkJ5JgZmj+/Yg+IUU5wcjW3mzjj07QrwP+Yp9QtVC+ThU64Wpp/5tTyzt5v0ZqrGwv35Dn0Z+3qeJ3fGhJlxeUyk0cieKggRCMnCxoUhmCGFJpkT1RULROYgJi6OwjeETgxjgAIjCAxaU4VSBD+9pOhTecjM/IXuStD32gKEvsb3eOLk98LcsvYlXzADnmsRDXqKabjC5yPfiwHnUvc8a2icFfOJt7euE5jjjFD5MbJH/dKp7m935meRImSX/O1pSofGfSntRZ9daArB5Y5GXQOCl50xXpDA3tqbg8r1YiUy+4tYfHn3r6A08GDra1Mx3ckjY+75kYwxz7QwuoORcT8+Cr71o/YHikugl4QKDeU3MrTRbkCQY31j99lGY8KweFA6q7oT3YuNDCBsME/dPPsqpJuacHqJUpTqIAULPfdM=
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
